config/routes.rb
Twiki::Application.routes.draw do

  get "upgrade/show"

  post "upgrade/create"

  devise_for :users

  resources :users

  resources :wikis do
    resources :sections, only: [:create]
  end

  resources :sections, except: [:create]

  get "welcome/index"

  root to: "welcome#index"

end

app/models/section.rb
class Section
  include Mongoid::Document
  include Mongoid::Timestamps

  # TODO - decide if this should be before_save or before_update
  before_update :save_old_version

  attr_accessible :title, :content, :internal_id

  # Define fields
  field :title, type: String
  field :content, type: String
  field :internal_id, type: Integer
  field :diffs, type: Array, default: []

  # Define relations
  belongs_to :author, class_name: "User", inverse_of: :sections
  belongs_to :wiki, inverse_of: :sections
  # belongs_to :master_version, class_name: "Section", inverse_of: :old_versions
  # embeds_many :old_versions, class_name: "Section", inverse_of: :master_version

  # Validate fields
  validates_presence_of :title, :internal_id, :content
  validates :wiki, presence: true
  validates :author, presence: true

  protected

  def save_old_version
    self.diffs << self.changes
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Slug
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  attr_accessible :account_type, :wikis, :sections, :viewable_wikis, :editable_wikis

  # Add username to model
  field :name,               :type => String
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  field :account_type,       :type => String, :default => "free"
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time
  field :remember_created_at, :type => Time
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  field :customer_id,        :type => String

  # Create slug on unique name (username) field
  slug :name

  # Define relations
  has_many :wikis, inverse_of: :author
  has_many :sections, inverse_of: :author
  has_and_belongs_to_many :viewable_wikis, class_name: "Wiki", inverse_of: :viewers
  has_and_belongs_to_many :editable_wikis, class_name: "Wiki", inverse_of: :collaborators

  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

end

app/models/wiki.rb
class Wiki

  include Mongoid::Document
  include Mongoid::Slug

  attr_accessible :title, :public, :viewers, :collaborators, :author_id

  field :title, type: String
  field :public, type: Boolean, :default => true

  # Define relations
  belongs_to :author, class_name: "User", inverse_of: :wikis
  has_many :sections, inverse_of: :wiki
  has_and_belongs_to_many :viewers, class_name: "User", inverse_of: :viewable_wikis
  has_and_belongs_to_many :collaborators, class_name: "User", inverse_of: :editable_wikis

  validates_presence_of :author
  validates_presence_of :title
  validates_uniqueness_of :title

  # Define slug on title field
  slug :title

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # TODO - add authentication / authorization - cancan or here?
  # before_filter :authenticate_user!, :except => [:index]
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def create
    puts params.inspect
    @section = Section.new(params[:section])
    @wiki = Wiki.find(params[:wiki_id])
    @section.wiki = @wiki
    @section.author = current_user
    if @section.save
      redirect_to @section, message: "Section saved successfully."
    else
      flash[:error] = "Error saving section. Please try again with valid data."
      render :new
    end
  end

  def new
    @section = Section.new
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update_attributes(params[:section])
      redirect_to @section, message: "Section saved successfully."
    else
      flash[:error] = "Error saving section. Please try again with valid data."
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to sections_path
  end

  def edit
    @section = Section.find(params[:id])
  end
end

app/controllers/upgrade_controller.rb
class UpgradeController < ApplicationController
  def show
    @user = current_user
  end

  def create
    @user = current_user
    Stripe.api_key = Rails.configuration.stripe[:secret_key]

    # Get the credit card details submitted by the form
    if token = params[:stripeToken]
      # Add conditional for valid payment info
      customer = Stripe::Customer.create(
        :card => token,
        :plan => "premium",
        :email => @user.email
      )

      @user.customer_id = customer
      @user.account_type = "premium"
      @user.save
      redirect_to @user, message: "Account successfully upgraded. You are now a premium user - thanks for using Twiki!"
    else
      flash[:error] = "Payment information not valid. Please try again with valid information."
      render :show
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      render wikis_path
    else
      render :layout => "welcome"
    end
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def create
    @user = current_user
    @wiki = Wiki.new(params[:wiki])
    @wiki.author = @user
    if @wiki.save
      redirect_to @wiki, notice: "Wiki was saved successfully."
    else
      flash[:error] = "There was a problem saving your wiki. Please try again."
      render :new
    end
  end

  def new
    @wiki = Wiki.new
  end

  def show
    @wiki = Wiki.find(params[:id])
    @sections = @wiki.sections
  end

  def index
    @wikis = Wiki.all
  end

  def update
    @wiki = Wiki.find(params[:id])
    if @wiki.update_attributes(params[:wiki])
      redirect_to @wiki, notice: "Wiki was updated successfully."
    else
      puts "Error!"
      flash[:error] = "There was an error updating your wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    @wiki.destroy
    redirect_to wikis_path
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def control_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'control-group error'
    else
      content_tag :div, capture(&block), class: 'control-group'
    end
  end
  
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/upgrade_helper.rb
module UpgradeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wiki_helper.rb
module WikiHelper
end

app/views/layouts/application.html.haml
/ !DOCTYPE HAML
%html{html_attrs("en-US")}
%head
  %title Twiki
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "https://js.stripe.com/v1", "application"
  = csrf_meta_tags
  = tag :meta, :name => "stripe-key", :content => Rails.configuration.stripe[:publishable_key]

%body

  .container
    / navigation bar
    %ul.nav.nav-tabs
      %li= link_to "Twiki", welcome_index_path
      .pull-right.user-info
        - if current_user
          Hello #{link_to (current_user.name || current_user.email), current_user}!
          = link_to edit_user_registration_path, class: 'btn btn-mini' do
            %i.icon-user
          = link_to destroy_user_session_path, :method => :delete, class: 'btn btn-mini' do
            %i.icon-share-alt
        - else
          = link_to "Sign in", new_user_session_path
          or
          = link_to "Sign up", new_user_registration_path
    / end navigation bar

    / flash messages
    - if flash[:notice]
      .alert.alert-success
        %button{:type => "button", "data-dismiss" => "alert"}close &times;
        = flash[:notice]
    - elsif flash[:error]
      .alert.alert-error
        %button{:type => "button", "data-dismiss" => "alert"}close &times;
        = flash[:error]
    - elsif flash[:alert]
      .alert
        %button{:type => "button", "data-dismiss" => "alert"}close &times;
    / end flash messages

    = yield

app/views/layouts/welcome.html.haml
%html{html_attrs("en-US")}
%head
  %title Twiki
  = stylesheet_link_tag       "application", :media => "all"
  = javascript_include_tag    "application"
  = csrf_meta_tags

%body

  .container
    %ul.nav.nav-tabs
      .pull-right
        = link_to "Sign in", new_user_session_path

    = yield

app/views/sections/create.html.erb
<h1>Sections#create</h1>
<p>Find me in app/views/sections/create.html.erb</p>

app/views/sections/destroy.html.erb
<h1>Sections#destroy</h1>
<p>Find me in app/views/sections/destroy.html.erb</p>

app/views/sections/edit.html.erb
<h1>Sections#edit</h1>
<p>Find me in app/views/sections/edit.html.erb</p>

app/views/sections/index.html.erb
<h1>Sections#index</h1>
<p>Find me in app/views/sections/index.html.erb</p>

app/views/sections/new.html.erb
<h1>Sections#new</h1>
<p>Find me in app/views/sections/new.html.erb</p>

app/views/sections/show.html.erb
<h1>Sections#show</h1>
<p>Find me in app/views/sections/show.html.erb</p>

app/views/sections/update.html.erb
<h1>Sections#update</h1>
<p>Find me in app/views/sections/update.html.erb</p>

app/views/upgrade/show.html.haml
.container
  .span8.offset2
    .span12
      %h1 Upgrade to a premium account
      %p Premium users get the following benefits:
      %ul
        %li Create private wikis
        %li Add as many collaborators to your wiki as you like
      %p Ready to take things to the next level?
      %P Go ahead:
      = form_tag upgrade_create_path do
        %article
          %label.amount
            %span Premium Plan: $10.00 / month

        %script{:src => "https://checkout.stripe.com/checkout.js", "class" => "stripe-button", "data-key" => "#{Rails.configuration.stripe[:publishable_key]}", "data-description" => "A monthly subscription", "data-amount" => 1000}

app/views/upgrade/update.html.haml
%h1 Upgrade#update
%p Find me in app/views/upgrade/update.html.haml

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/index.html.haml
%h2.text-center Twiki: Social, Markdown Wikis

.row-fluid
  .hero-unit.span8.offset2
    .row-fluid.span8.offset2
      %h4.text-center Create and share Markdown Wikis
    .row-fluid.span4.offset4
      %p
      = link_to "Sign Up", new_user_session_path, class: 'btn btn-primary btn-block'

.row-fluid
  .span4.offset2
    %h3 Create as many public wikis as you want!
    %img
    %p.text-center Free Plan
  .span4
    %h3 Create private wikis!
    %img
    %p.text-center Premium Plan

app/views/wikis/create.html.erb
%h1 New Wiki

.row
  .span6
    %p

app/views/wikis/destroy.html.erb
<h1>Wiki#destroy</h1>
<p>Find me in app/views/wiki/destroy.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Wiki#edit</h1>
<p>Find me in app/views/wiki/edit.html.erb</p>

app/views/wikis/index.html.erb
<h1>Wiki#index</h1>
<p>Find me in app/views/wiki/index.html.erb</p>

app/views/wikis/new.html.haml
%h1 New Wiki
.row
  .span6
  %p Guidelines for new wikis:
  %ul
    %li Make sure content is appropriate
    %li Wikis must have unique names, so first check if your wiki already exists.
    %li Wikis created under free accounts are public. For private wikis, upgrade to a #{link_to "premium account", upgrade_path}.

app/views/wikis/show.html.erb
<h1>Wiki#show</h1>
<p>Find me in app/views/wiki/show.html.erb</p>

app/views/wikis/update.html.erb
<h1>Wiki#update</h1>
<p>Find me in app/views/wiki/update.html.erb</p>